# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - puretext-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend' # Correct path to the Azure Function code
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        # Point to requirements.txt in the backend folder
        run: pip install -r backend/requirements.txt

      # Check if Azure function files exist
      - name: Check Azure Function files
        run: |
          echo "Checking Azure Function files..."
          ls -la backend/azure_function
          if [ -f backend/azure_function/function.json ]; then
            echo "Function.json exists"
          else
            echo "Function.json not found"
          fi

      # Zip only the Azure Function folder
      - name: Zip artifact for deployment
        run: |
          cd backend/azure_function
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_70DE5D07F3A8432EA3F740B27A91AFBD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E082C8FC9F3F4D1997819CD641A22076 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A109925FBFDA42C798DC47AEAD6899C2 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'puretext-api'
          slot-name: 'Production'
          package: '.' # Use the extracted content from the zip
